In [6]:
import numpy as np
x= np.array(([2,9],[1,5],[3,6]),dtype= float)
y=np.array(([92],[86],[89]),dtype= float)
c= np.amax(x,axis=0)
print(c)
x=x/c
y=y/100
print(x)
print(y)

[3. 9.]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [7]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_grad(x):
    return x*(1-x)

In [8]:
epoch=1000
eta=0.1
input_neurons=2
hidden_neurons=3
output_neurons=1

wh=np.random.uniform(size=(input_neurons,hidden_neurons))
print(wh)
bh=np.random.uniform(size=(1,hidden_neurons))
print(bh)
wout=np.random.uniform(size=(hidden_neurons,output_neurons))
print(wout)
bout=np.random.uniform(size=(1,output_neurons))
print(bout)

[[0.65264821 0.62887702 0.5970444 ]
 [0.59087162 0.18987399 0.74788479]]
[[0.00750303 0.31406397 0.53450128]]
[[0.64697465]
 [0.48613899]
 [0.25438819]]
[[0.79651886]]


In [9]:
for i in range(epoch):
    h_ip=np.dot(x,wh)+bh
    print(h_ip)
    h_act= sigmoid(h_ip)
    o_ip=np.dot(h_act,wout)+bout
    output= sigmoid(o_ip)
    
    Eo=y-output
    outgrad= sigmoid_grad(output)
    d_output = Eo* outgrad
    print("the d_output is \n",d_output)
    
    Eh=d_output.dot(wout.T)
    hiddengrad= sigmoid_grad(h_act)
    d_hidden= Eh *hiddengrad
    wout += h_act.T.dot(d_output)*eta
    wh += x.T.dot(d_hidden)*eta


[[1.03347346 0.9231893  1.68041567]
 [0.55331445 0.62917519 1.14900763]
 [1.05406566 1.06952365 1.63013554]]
the d_output is 
 [[0.00682155]
 [0.00157227]
 [0.00302281]]
[[1.03366516 0.92333752 1.68046858]
 [0.55341716 0.62925462 1.14903598]
 [1.05425028 1.06966619 1.63018653]]
the d_output is 
 [[0.00678297]
 [0.00154035]
 [0.00299013]]
[[1.03385548 0.92348475 1.68052123]
 [0.55351913 0.62933352 1.14906419]
 [1.05443356 1.06980777 1.63023726]]
the d_output is 
 [[0.00674485]
 [0.00150883]
 [0.00295787]]
[[1.03404442 0.923631   1.68057362]
 [0.55362037 0.6294119  1.14909225]
 [1.05461551 1.0699484  1.63028774]]
the d_output is 
 [[0.0067072 ]
 [0.0014777 ]
 [0.00292601]]
[[1.03423202 0.92377628 1.68062575]
 [0.55372088 0.62948975 1.14912018]
 [1.05479613 1.07008807 1.63033796]]
the d_output is 
 [[0.00667   ]
 [0.00144694]
 [0.00289455]]
[[1.03441827 0.92392059 1.68067762]
 [0.55382068 0.62956709 1.14914797]
 [1.05497545 1.07022681 1.63038793]]
the d_output is 
 [[0.00663325]
 [0.00141

In [10]:
print("Normalized input: \n"+str(x))
print("Actual output: \n"+ str(y))
print("Predicted output: \n",output)

Normalized input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
 [[0.89451311]
 [0.87906677]
 [0.89607708]]
